### ISSUE TITLE
Can't find module with 1.1.7

### ISSUE THREAD

**Issue by MathieuLoutre** [sgwilym/windups#15]
Hello! It seems like the new version 1.1.7 creates some issues and the module can't be located anymore. It seems to have something to do with: https://github.com/sgwilym/windups/blob/master/package.json#L28

There's no file called `index-.js`. Possibly a mistake in the new build system?

**Comment by gurkerl83** [comment]
@MathieuLoutre I can confirm this problem. In my opinion, main and module fields should be enough in package.json. The NPM doc says this property's purpose is to limit which files a consumer can import/require. Maybe it was not intentional to add this declaration. As the NPM documentation says, it got added in NPM 7. In package.json, there are a few fields Yarn / Yarn 2 (Berry) support, but NPM does not, such as the field "resolutions." Hopefully, this is not true vice versa for the field "exports." 

@sgwilym Can you please investigate or remove this configuration option, thx!

**Comment by sgwilym** [comment]
@MathieuLoutre Oh, whoops. Thanks for reporting this. I just published v1.1.8, where the `require` export points at an actual, existing file. Please let me know if you have any further trouble.

@gurkerl83 I won't be removing these extra fields!

**Comment by gurkerl83** [comment]
@sgwilym It seems with v1.1.8, this error is gone, but another unveils itself. The problem is that your library break-styled-lines does not provide a commonJS output yet. When the loading of windups starts as a commonJS module, the respective counterpart of break-styled-lines in a commonJS format is required. Maybe you can tsdx the library as well, thx!
