### ISSUE TITLE
Where is the doc website source ?

### ISSUE THREAD

**Issue by beaussan** [sgwilym/windups#5]
Hi,

First of all, your library is awesome !

I love the doc site, and I would love to be able to look at the source code of the doc website to learn in a real world example project :)

I understand if you don't want it to be public tho !

**Comment by sgwilym** [comment]
Hi, thank you for the kind words @beaussan!

The doc site's source is not open, simply because... it's a bit messy! And I wasn't sure if that'd be a good example or not.

I understand how useful it could be to see a 'real world example' though, so how about this: I can give you access to the windups docs repo, you let me know whether I'm worrying about nothing or not, and maybe we make it public from there?

**Comment by beaussan** [comment]
Sure! I can look at it next week! Thank you for your trust :)

**Comment by beaussan** [comment]
It looks great ! And I got a better feel for the library thanks to it ! Great work on both !! =D

**Comment by sgwilym** [comment]
Well that's good enough for me. The repo for the docs site is now public at https://github.com/sgwilym/windups-docs. I hope it makes a useful reference!
